/** Declaration file generated by dts-gen */

export function debug(log: any, store: boolean): void;

export function error(log: any, store: boolean): void;

export function fatal(log: any, store: boolean): void;

export function info(log: any, store: boolean): void;

export function warning(log: any, store: boolean): void;

